[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-mini-1-n4
framework = arduino
monitor_speed = 500000

board_build.filesystem = littlefs
board_build.partitions = src/partitions_4mb.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Optimized stack sizes
    #-D CONFIG_ASYNC_TCP_STACK_SIZE=6144
    #-D CONFIG_LWIP_TCPIP_TASK_STACK_SIZE=3072
    #-D CONFIG_ESP_MAIN_TASK_STACK_SIZE=6144
    
     # Network optimization
    -D CONFIG_LWIP_MAX_SOCKETS=8
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D CONFIG_ASYNC_TCP_USE_WDT=0
    
lib_deps = 
    # Lightweight web server
    mathieucarbou/AsyncTCP@^3.1.4
    mathieucarbou/ESP Async WebServer@^3.0.6
    bblanchon/ArduinoJson@^7.0.0
    
    # Existing dependencies
    https://github.com/Freenove/Freenove_WS2812_Lib_for_ESP32
    https://github.com/rwmingis/InterruptButton
    https://github.com/vortigont/ESPAsyncButton

lib_ignore = 
    AsyncTCP_RP2040W
    AsyncTCP_SSL
    ESPUI

monitor_filters = 
    esp32_exception_decoder
    colorize
[env:lilygo-t2can-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32s3box
framework = arduino
monitor_speed = 500000

board_build.filesystem = littlefs
board_build.partitions = src/partitions_4mb.csv

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_LWIP_MAX_SOCKETS=8
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D CONFIG_ASYNC_TCP_USE_WDT=0
    -D OH_BOARD_T2CAN=1
    -D OH_CAN_HALDEX_MCP2515=1

lib_deps =
    mathieucarbou/AsyncTCP@^3.1.4
    mathieucarbou/ESP Async WebServer@^3.0.6
    bblanchon/ArduinoJson@^7.0.0
    autowp/autowp-mcp2515@^1.1.0
    https://github.com/Freenove/Freenove_WS2812_Lib_for_ESP32
    https://github.com/rwmingis/InterruptButton
    https://github.com/vortigont/ESPAsyncButton

lib_ignore =
    AsyncTCP_RP2040W
    AsyncTCP_SSL
    ESPUI
